### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by spade101** [dshukertjr/twitter_clone#2]
how can i fix this errors

profile page

floatingActionButton: FloatingActionButton(
        onPressed: () async {
          final roomId = await roomsStateNotifier.createRoom(_userId);

  //mounted has error

          if (context.mounted) {
            Navigator.of(context).push(ChatPage.route(roomId));
          }
        },

homepage

 @override
  Widget build(BuildContext context) {
    return Stack(
      clipBehavior: Clip.none,
      children: [
        Icon(iconData),
        if (badgeCount > 0)
          Positioned(
            right: -6,
            top: -6,

//Badge error

            child: Badge.count(
              count: badgeCount,
              backgroundColor: Theme.of(context).primaryColor,
            ),
          ),
      ],
    );
  }

**Comment by dshukertjr** [comment]
@spade101 You can update your Flutter version to the latest one!

**Comment by spade101** [comment]
thank you. it work. im new to coding

**Comment by dshukertjr** [comment]
Welcome to Flutter!
