### ISSUE TITLE
login error

### ISSUE THREAD

**Issue by fadleyfrost** [dshukertjr/twitter_clone#3]
hello i think there is an error in login it only sent confirmation to an email address again and again it wont direct a user to a homepage. it was stack on login it only say email confirmation sent and when i confirm my email and login it say email confirmation again

**Comment by dshukertjr** [comment]
@fadleyfrost 
Just to summarize what you are saying, after clicking on the login link on the email, it opens the app's login page again?
What device are you using?

**Comment by fadleyfrost** [comment]
sir when i click on login on email it says local host refused to connect.

**Comment by fadleyfrost** [comment]
my internet connection is good. maybe im doing it wrong what did i miss
